import Header from "@/components/Header";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { JetBrains_Mono } from "next/font/google";
import PageTransition from "@/components/PageTransition";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700","800", ],
  subsets: ["latin"],
})

export const metadata = {
  title: "RK Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jetBrainsMono.variable} h-full antialiased`}
    >
      <body className={jetBrainsMono.variable}>
        
        <TooltipProvider>
        <Header/>
        <PageTransition>
           {children}
        </PageTransition>
       </TooltipProvider></body>
    </html>
  );
}
