import Header from "@/components/Header";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { JetBrains_Mono } from "next/font/google";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "RK Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jetBrainsMono.variable} min-h-screen w-full antialiased`}>
      <body className="bg-[#1c1c22] text-white flex flex-col min-h-screen w-full m-0 lg:px-20 px-4 overflow-x-hidden">
        <TooltipProvider>
          <Header />
          <StairTransition />
          <PageTransition>
            <main className="w-full flex-1">
              {children}
            </main>
          </PageTransition>
        </TooltipProvider>
      </body>
    </html>
  );
}